# Copyright 2023 the Limbo authors. All rights reserved. MIT license.

[workspace]
resolver = "2"
members = [
  "bindings/wasm",
  "cli",
  "sqlite3",
  "core",
  "simulator",
]
exclude = ["perf/latency/limbo"]

[workspace.package]
version = "0.0.3"
authors = ["the Limbo authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/penberg/limbo"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.19.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Path that installers should place binaries in
install-path = "~/.limbo"
# Whether to install an updater program
install-updater = true
# Whether to consider the binaries in a package for distribution (defaults true)
dist = false
# Whether to enable GitHub Attestations
github-attestations = true

[profile.dist]
inherits = "release"
lto = "thin"
